export const promptsArray = [
  { id: "base-1", prompt: "The uglier the selfie you take, the better it is", "frame_type": "horizontal" },
  { id: "base-2", prompt: "What's the view from your window?", "frame_type": "horizontal" },
  { id: "base-3", prompt: "Take a photo that shows how your day feels.", "frame_type": "horizontal" },
  { id: "base-4", prompt: "Put something ridiculous on your head", "frame_type": "horizontal" },
  { id: "base-5", prompt: "Open the fridge", "frame_type": "horizontal" },
  { id: "base-6", prompt: "Send your side of a hug.", "frame_type": "horizontal" },
  { id: "base-7", prompt: "Together, build an animal using only your hands", "frame_type": "horizontal" },
  { id: "base-8", prompt: "Take a mirror picture in your fav room", "frame_type": "horizontal" },
  { id: "base-9", prompt: "Be your half of a heart", "frame_type": "horizontal" },
  { id: "base-10", prompt: "Build a face using 3 objects on your desk", "frame_type": "horizontal" },
  { id: "base-11", prompt: "What are you drinking?", "frame_type": "horizontal" },
  { id: "base-12", prompt: "Send a kiss through the photo", "frame_type": "horizontal" },
  { id: "base-13", prompt: "Find a round shape", "frame_type": "horizontal" },
  { id: "base-14", prompt: "What are you eating", "frame_type": "horizontal" },
  { id: "base-15", prompt: "Something you'd share if you were in the same room right now.", "frame_type": "horizontal" },
  { id: "base-16", prompt: "Snap something blue", "frame_type": "horizontal" },
  { id: "base-17", prompt: "How is your mood today? No words allowed!", "frame_type": "horizontal" },
  { id: "base-18", prompt: "Capture something that feels like 'home' to you", "frame_type": "horizontal" },
  { id: "base-19", prompt: "Snap something that makes you happy", "frame_type": "horizontal" },
  { id: "base-20", prompt: "Sky check! Do we need sunglasses or umbrellas today?", "frame_type": "horizontal" },
  { id: "base-21", prompt: "Take a photo of something you know they'd love.", "frame_type": "horizontal" },
  { id: "base-22", prompt: "Snap the smallest thing around you", "frame_type": "horizontal" },
  { id: "base-23", prompt: "A color that describes your day so far", "frame_type": "horizontal" },
  { id: "base-24", prompt: "Find something that reminds you of me", "frame_type": "horizontal" },
  { id: "base-25", prompt: "What's the greenest thing you can spot? GO!", "frame_type": "horizontal" },
  { id: "base-26", prompt: "Take a photo of one shoe", "frame_type": "horizontal" },
  { id: "base-27", prompt: "Capture a moment that feels like 'us,' even when we're apart", "frame_type": "horizontal" },
  { id: "base-28", prompt: "Find the most colorful thing around you", "frame_type": "horizontal" },
  { id: "base-29", prompt: "Snap a pic of half your outfit", "frame_type": "horizontal" },
  { id: "base-30", prompt: "Look up. Snap the first thing you see.", "frame_type": "horizontal" },
  { id: "base-31", prompt: "What's the last thing you touched before opening this app?", "frame_type": "horizontal" },
  { id: "base-32", prompt: "Zoom in way too much on something. Let us guess what it is", "frame_type": "horizontal" },
  { id: "base-33", prompt: "Send a photo of the book, show, or screen you're staring at right now.", "frame_type": "horizontal" },
  { id: "base-34", prompt: "Look to your left like your friend is about to say something shocking.", "frame_type": "horizontal" },
  { id: "base-35", prompt: "What color is your day today?", "frame_type": "horizontal" },
  { id: "base-36", prompt: "Take a photo of your face or body halfway cropped — let your friend become the other half.", "frame_type": "horizontal" },
  { id: "base-37", prompt: "What's in front of you?", "frame_type": "horizontal" },
  { id: "base-38", prompt: "Show me the tiniest thing you can find around you", "frame_type": "horizontal" },
  { id: "base-39", prompt: "Look up - what are u seeing?", "frame_type": "horizontal" },
  { id: "base-40", prompt: "What's your phone cover?", "frame_type": "horizontal" },
  { id: "base-41", prompt: "Show your eyes", "frame_type": "horizontal" },
  { id: "base-42", prompt: "Snap an object with your name initial", "frame_type": "horizontal" },
  { id: "base-43", prompt: "Is it a bad or a good hair day?", "frame_type": "horizontal" },
  { id: "base-44", prompt: "Capture your reflection — in a mirror, window, or even a spoon!", "frame_type": "horizontal" },
  { id: "base-45", prompt: "Capture your “Monday morning” face — even if it's not Monday!", "frame_type": "horizontal" },
  { id: "base-46", prompt: "Find a plant or flower and snap it", "frame_type": "horizontal" },
  { id: "base-47", prompt: "Show me your socks of the day", "frame_type": "horizontal" },
  { id: "base-48", prompt: "Make your best “duck face”", "frame_type": "horizontal" },
  { id: "base-49", prompt: "FIT CHECK!", "frame_type": "horizontal" },
  { id: "base-50", prompt: "Snap an object with the initial of your match's name", "frame_type": "horizontal" }
];
