export const promptsArray = [
  { id: "base-1", prompt: "the uglier the selfie you take, the better it is", "frame_type": "horizontal" },
  { id: "base-2", prompt: "what's the view from your window?", "frame_type": "horizontal" },
  { id: "base-3", prompt: "take a photo that shows how your day feels.", "frame_type": "horizontal" },
  { id: "base-4", prompt: "put something ridiculous on your head", "frame_type": "horizontal" },
  { id: "base-5", prompt: "open the fridge", "frame_type": "horizontal" },
  { id: "base-6", prompt: "send your side of a hug.", "frame_type": "horizontal" },
  { id: "base-7", prompt: "together, build an animal using only your hands", "frame_type": "horizontal" },
  { id: "base-8", prompt: "take a mirror picture in your fav room", "frame_type": "horizontal" },
  { id: "base-9", prompt: "be your half of a heart", "frame_type": "horizontal" },
  { id: "base-10", prompt: "build a face using 3 objects on your desk", "frame_type": "horizontal" },
  { id: "base-11", prompt: "what are you drinking?", "frame_type": "horizontal" },
  { id: "base-12", prompt: "send a kiss through the photo", "frame_type": "horizontal" },
  { id: "base-13", prompt: "find a round shape", "frame_type": "horizontal" },
  { id: "base-14", prompt: "what are you eating", "frame_type": "horizontal" },
  { id: "base-15", prompt: "something you'd share if you were in the same room right now.", "frame_type": "horizontal" },
  { id: "base-16", prompt: "snap something blue", "frame_type": "horizontal" },
  { id: "base-17", prompt: "how is your mood today? no words allowed!", "frame_type": "horizontal" },
  { id: "base-18", prompt: "capture something that feels like 'home' to you", "frame_type": "horizontal" },
  { id: "base-19", prompt: "snap something that makes you happy", "frame_type": "horizontal" },
  { id: "base-20", prompt: "sky check! Do we need sunglasses or umbrellas today?", "frame_type": "horizontal" },
  { id: "base-21", prompt: "take a photo of something you know they'd love.", "frame_type": "horizontal" },
  { id: "base-22", prompt: "snap the smallest thing around you", "frame_type": "horizontal" },
  { id: "base-23", prompt: "a color that describes your day so far", "frame_type": "horizontal" },
  { id: "base-24", prompt: "find something that reminds you of me", "frame_type": "horizontal" },
  { id: "base-25", prompt: "what's the greenest thing you can spot? GO!", "frame_type": "horizontal" },
  { id: "base-26", prompt: "take a photo of one shoe", "frame_type": "horizontal" },
  { id: "base-27", prompt: "capture a moment that feels like 'us,' even when we're apart", "frame_type": "horizontal" },
  { id: "base-28", prompt: "find the most colorful thing around you", "frame_type": "horizontal" },
  { id: "base-29", prompt: "snap a pic of half your outfit", "frame_type": "horizontal" },
  { id: "base-30", prompt: "look up. snap the first thing you see.", "frame_type": "horizontal" },
  { id: "base-31", prompt: "what's the last thing you touched before opening this app?", "frame_type": "horizontal" },
  { id: "base-32", prompt: "zoom in way too much on something. let us guess what it is", "frame_type": "horizontal" },
  { id: "base-33", prompt: "send a photo of the book, show, or screen you're staring at right now.", "frame_type": "horizontal" },
  { id: "base-34", prompt: "look to your left like your friend is about to say something shocking.", "frame_type": "horizontal" },
  { id: "base-35", prompt: "what color is your day today?", "frame_type": "horizontal" },
  { id: "base-36", prompt: "take a photo of your face or body halfway cropped — let your friend become the other half.", "frame_type": "horizontal" },
  { id: "base-37", prompt: "what's in front of you?", "frame_type": "horizontal" },
  { id: "base-38", prompt: "show me the tiniest thing you can find around you", "frame_type": "horizontal" },
  { id: "base-39", prompt: "look up - what are u seeing?", "frame_type": "horizontal" },
  { id: "base-40", prompt: "what's your phone cover?", "frame_type": "horizontal" },
  { id: "base-41", prompt: "show your eyes", "frame_type": "horizontal" },
  { id: "base-42", prompt: "snap an object with your name initial", "frame_type": "horizontal" },
  { id: "base-43", prompt: "is it a bad or a good hair day?", "frame_type": "horizontal" },
  { id: "base-44", prompt: "capture your reflection — in a mirror, window, or even a spoon!", "frame_type": "horizontal" },
  { id: "base-45", prompt: "capture your “monday morning” face — even if it's not monday!", "frame_type": "horizontal" },
  { id: "base-46", prompt: "find a plant or flower and snap it", "frame_type": "horizontal" },
  { id: "base-47", prompt: "show me your socks of the day", "frame_type": "horizontal" },
  { id: "base-48", prompt: "make your best “duck face”", "frame_type": "horizontal" },
  { id: "base-49", prompt: "FIT CHECK!", "frame_type": "horizontal" },
  { id: "base-50", prompt: "snap an object with the initial of your match's name", "frame_type": "horizontal" }
];
